server:
  port: 8081
spring:
  application:
    name: emotion-generate-service
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: http://47.115.3.112
      port: 32782
  zipkin:
    base-url: http://47.115.3.112:9411/
    service:
      name: ${spring.application.name}
  sleuth:
    sampler:
      probability: 1.0
    grpc:
      enabled: true
    web:
      client:
        enabled: true
grpc:
  server:
    port: 8082
logging:
  level:
    org.springframework.cloud.sleuth: trace
